language: php

php:
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - hhvm

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

env:
  matrix: SYMFONY_VERSION=3.2.*
  global:
    - SYMFONY_DEPRECATIONS_HELPER=weak

matrix:
  include:
    - php: 7.1
      env: SYMFONY_VERSION=3.3.* DEPS=dev
    - php: 5.5
      env: SYMFONY_VERSION=2.8.* COMPOSER_FLAGS="--prefer-lowest"
  fast_finish: true

before_install:
  - if [[ "$TRAVIS_PHP_VERSION" != "hhvm" ]]; then echo "memory_limit = -1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini; fi
  - phpenv config-rm xdebug.ini || true
  - composer self-update
  - if [ "$DEPS" = "dev" ]; then perl -pi -e 's/^}$/,"minimum-stability":"dev"}/' composer.json; fi
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require symfony/symfony:${SYMFONY_VERSION} --no-update; fi

install: composer update --prefer-dist $COMPOSER_FLAGS

before_script: vendor/symfony-cmf/testing/bin/travis/phpcr_odm_doctrine_dbal.sh

script: phpunit

notifications:
  irc: "irc.freenode.org#symfony-cmf"
  email: "symfony-cmf-devs@googlegroups.com"
